num1 = int(input("escolha o primeiro numero: "))
num2 = int(input("escolha o segundo numero: "))
num3 = int(input("escolha o terceiro numero: "))
num4 = int(input("escolha o quarto numero: "))
num5 = int(input("escolha o quinto numero: "))
print(num1 + num2 + num3 + num4 + num5)